

language: swift
osx_image: xcode9.4
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
- set -o pipefail
before_script: 
- gem install xcpretty

script:
- xcodebuild -project OMMeterTest/OMMeterTest.xcodeproj -scheme OMMeterTest -sdk iphonesimulator test | xcpretty -c
- pod lib lint --quick